coverage:
  status:
    project:
      default:
        threshold: 1%
comment:
  layout: "diff"
  behavior: once
  require_changes: true
  require_base: yes
  require_head: yes
  branches:
    - "master"
fixes:
  - "/opt/conda/lib/python3.8/site-packages/::project/"
